### PR TITLE
Added wrapper for FLAC__stream_decoder_skip_single_frame() to pyflac

### PR DESCRIPTION
**Pull request by Mysingen**
Hello Dan

I needed this functionality so I added the missing wrapper. Please pull.

BR / Klas

### CODE REVIEW

**Comment by dsully** [comment]
Klas - please fix the indentation, and I'll pull. Thanks.

**Comment by Mysingen** [comment]
Sorry about that. Tabs changed to 4 spaces now.

Is there any way to get to the enum values in libflac? I wanted to
compare StreamDecoder.get_state() against
FLAC__STREAM_DECODER_END_OF_STREAM.

BR / Klas

On Mon, Jun 13, 2011 at 12:59 AM, dsully
reply@reply.github.com
wrote:

**Comment by dsully** [comment]
I'll take a look at the enums.

**Comment by Mysingen** [comment]
Hello again. Have you done any work on a Python 3 version of pyflac?
I'm trying to get Dwite running on 3.2 and just started looking at
this.

/ Klas

On Mon, Jun 13, 2011 at 3:13 AM, dsully
reply@reply.github.com
wrote:

**Pull request merged**
